[profile.default]
solc_version = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
remappings=[
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@bob-collective/bitcoin-spv/=lib/bitcoin-spv/src/",
    "@bob-collective/bob/=lib/bob/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
